# generated by https://github.com/fox0/pas2py
print("Введите положительные числа A и B (A > B):")
print(" A = ", end="")
A = float(input())
print(" B = ", end="")
B = float(input())
while A >= B:
    A = A - B
print("Длина незанятой части отрезка A: ", A)
